name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.19'

    - name: Build
      run: go build -v ./...

    - name: golang-govulncheck-action
      uses: golang/govulncheck-action@v1.0.3
      with:
        go-version-input: '1.19'
        go-package: ./...